In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Life Expectancy Data.csv')

# to confirm the data is loaded in properly
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [ ]:
print(f"Shape (rows, columns): {df.shape}")
print(f"Size (rows * columns): {df.size}")

df.isnull().sum()

Shape (rows, columns): (2938, 22)
Size (rows * columns): 64636

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [ ]:
df = df.drop(['Population', 'Hepatitis B', 'GDP', 'percentage expenditure', 'Income composition of resources', 'Schooling'], axis=1)

In [ ]:
df['Life expectancy '] = df['Life expectancy '].fillna(df['Life expectancy '].median())
df['Adult Mortality'] = df['Adult Mortality'].fillna(df['Adult Mortality'].median())
df[' BMI '] = df[' BMI '].fillna(df[' BMI '].median())
df['Polio'] = df['Polio'].fillna(df['Polio'].median())
df['Diphtheria '] = df['Diphtheria '].fillna(df['Diphtheria '].median())
df[' thinness  1-19 years'] = df[' thinness  1-19 years'].fillna(df[' thinness  1-19 years'].median())
df[' thinness 5-9 years'] = df[' thinness 5-9 years'].fillna(df[' thinness 5-9 years'].median())
df['Alcohol'] = df['Alcohol'].fillna(df['Alcohol'].median())

In [ ]:
# Dropped all rows with missing values
# df.dropna(inplace=True)
df.isnull().sum()

Country                     0
Year                        0
Status                      0
Life expectancy             0
Adult Mortality             0
infant deaths               0
Alcohol                   194
percentage expenditure      0
Measles                     0
 BMI                        0
under-five deaths           0
Polio                       0
Total expenditure         226
Diphtheria                  0
 HIV/AIDS                   0
 thinness  1-19 years      34
 thinness 5-9 years        34
dtype: int64

In [ ]:
print(df.columns)

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Measles ',
       ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', ' thinness  1-19 years',
       ' thinness 5-9 years'],
      dtype='object')

In [ ]:
plt.scatter(df[' thinness  1-19 years'], df['Life expectancy '])
plt.xlabel('Thinness')
plt.ylabel('Life Expectancy')
plt.title('Thinness vs Life Expectancy')
plt.ticklabel_format(style='plain')
plt.show()

plt.scatter(df[' BMI '], df['Life expectancy '])
plt.xlabel('BMI')
plt.ylabel('Life Expectancy')
plt.title('BMI vs Life Expectancy')
plt.ticklabel_format(style='plain')
plt.show()

plt.scatter(df['Adult Mortality'], df['Life expectancy '])
plt.xlabel('Adult Mortality')
plt.ylabel('Life Expectancy')
plt.title('Adult Mortality vs Life Expectancy')
plt.ticklabel_format(style='plain')
plt.show()

plt.scatter(df['Alcohol'], df['Life expectancy '])
plt.xlabel('Alcohol')
plt.ylabel('Life Expectancy')
plt.title('Alcohol vs Life Expectancy')
plt.ticklabel_format(style='plain')
plt.show()

plt.scatter(df['Measles '], df['Life expectancy '])
plt.xlabel('Measles')
plt.ylabel('Life Expectancy')
plt.title('Measles vs Life Expectancy')
plt.ticklabel_format(style='plain')
plt.show()

NameError: name 'plt' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns

In [ ]:
x = df[['Physical Activity Level', 'Stress Level', 'Sleep Duration']]
y = df['Life expectancy']

sleepQuality_model = LinearRegression()
sleepQuality_model.fit(x, y)

coefficients = sleepQuality_model.coef_
intercept = sleepQuality_model.intercept_

# Printing the intercept and coefficients
print("Intercept:", intercept)
print("Coefficients:")
for i, coef in enumerate(coefficients):
    print(f"{i + 1}: {coef}")